version: '3.8'

services:
  tehkly_db:
    container_name: tehkly_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - tehkly_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  tehkly_backend:
    container_name: tehkly_backend
    image: ${DOCKER_USER}/tehkly-backend:latest
    build:
      context: ./tehkly-core
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@tehkly_db:${DB_PORT}/${DB_NAME}
      # Ou separado:
      - DB_HOST=tehkly_db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AUTH_API_URL=${AUTH_API_URL}
    depends_on:
      tehkly_db:
        condition: service_healthy
    restart: always
    networks:
      - tehkly_network
      - proxy_network

  tehkly_frontend:
    container_name: tehkly_frontend
    image: ${DOCKER_USER}/tehkly-frontend:latest
    build:
      context: ./tehkly-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # - NEXT_PUBLIC_API_URL=http://tehkly_backend:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - tehkly_backend
    restart: always
    networks:
      - tehkly_network
      - proxy_network

networks:
  tehkly_network:
    driver: bridge
  proxy_network:
    external: true

volumes:
  postgres_data:
    driver: local